services:
  - type: web
    name: YourAppName
    env: python
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y chromium-browser
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: /usr/bin/chromium-browser